name: Build iOS

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macOS-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install npm dependencies
        run: npm ci

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2

      - name: Install CocoaPods
        run: sudo gem install cocoapods

      - name: Install iOS pods
        working-directory: ios
        run: pod install

      - name: Build iOS app
        working-directory: ios
        run: |
          xcodebuild build \
          -workspace acessoOn.xcworkspace \
          -scheme acessoOn \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest'

      - name: Archive for distribution
        working-directory: ios
        run: |
          xcodebuild archive \
          -workspace acessoOn.xcworkspace \
          -scheme acessoOn \
          -configuration Release \
          -archivePath $PWD/build/acessoOn.xcarchive

          xcodebuild -exportArchive \
          -archivePath $PWD/build/acessoOn.xcarchive \
          -exportOptionsPlist ExportOptions.plist \
          -exportPath $PWD/build

      - name: Upload IPA
        uses: actions/upload-artifact@v4  # Alterado para v4!
        if: success()
        with:
          name: acessoOn-iOS
          path: ios/build/**/*.ipa  # Caminho com wildcard para encontrar o .ipa